"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import nebius.common.v1.metadata_pb2
import nebius.common.v1.operation_pb2
import nebius.common.v1.operation_service_pb2
import nebius.compute.v1.instance_pb2
import nebius.compute.v1.instance_service_pb2
import nebius.compute.v1.operation_service_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class InstanceServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Get: grpc.UnaryUnaryMultiCallable[
        nebius.compute.v1.instance_service_pb2.GetInstanceRequest,
        nebius.compute.v1.instance_pb2.Instance,
    ]

    GetByName: grpc.UnaryUnaryMultiCallable[
        nebius.common.v1.metadata_pb2.GetByNameRequest,
        nebius.compute.v1.instance_pb2.Instance,
    ]

    List: grpc.UnaryUnaryMultiCallable[
        nebius.compute.v1.instance_service_pb2.ListInstancesRequest,
        nebius.compute.v1.instance_service_pb2.ListInstancesResponse,
    ]

    Create: grpc.UnaryUnaryMultiCallable[
        nebius.compute.v1.instance_service_pb2.CreateInstanceRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

    Update: grpc.UnaryUnaryMultiCallable[
        nebius.compute.v1.instance_service_pb2.UpdateInstanceRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

    Delete: grpc.UnaryUnaryMultiCallable[
        nebius.compute.v1.instance_service_pb2.DeleteInstanceRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

    Start: grpc.UnaryUnaryMultiCallable[
        nebius.compute.v1.instance_service_pb2.StartInstanceRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

    Stop: grpc.UnaryUnaryMultiCallable[
        nebius.compute.v1.instance_service_pb2.StopInstanceRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

    ListOperationsByParent: grpc.UnaryUnaryMultiCallable[
        nebius.compute.v1.operation_service_pb2.ListOperationsByParentRequest,
        nebius.common.v1.operation_service_pb2.ListOperationsResponse,
    ]

class InstanceServiceAsyncStub:
    Get: grpc.aio.UnaryUnaryMultiCallable[
        nebius.compute.v1.instance_service_pb2.GetInstanceRequest,
        nebius.compute.v1.instance_pb2.Instance,
    ]

    GetByName: grpc.aio.UnaryUnaryMultiCallable[
        nebius.common.v1.metadata_pb2.GetByNameRequest,
        nebius.compute.v1.instance_pb2.Instance,
    ]

    List: grpc.aio.UnaryUnaryMultiCallable[
        nebius.compute.v1.instance_service_pb2.ListInstancesRequest,
        nebius.compute.v1.instance_service_pb2.ListInstancesResponse,
    ]

    Create: grpc.aio.UnaryUnaryMultiCallable[
        nebius.compute.v1.instance_service_pb2.CreateInstanceRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

    Update: grpc.aio.UnaryUnaryMultiCallable[
        nebius.compute.v1.instance_service_pb2.UpdateInstanceRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

    Delete: grpc.aio.UnaryUnaryMultiCallable[
        nebius.compute.v1.instance_service_pb2.DeleteInstanceRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

    Start: grpc.aio.UnaryUnaryMultiCallable[
        nebius.compute.v1.instance_service_pb2.StartInstanceRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

    Stop: grpc.aio.UnaryUnaryMultiCallable[
        nebius.compute.v1.instance_service_pb2.StopInstanceRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

    ListOperationsByParent: grpc.aio.UnaryUnaryMultiCallable[
        nebius.compute.v1.operation_service_pb2.ListOperationsByParentRequest,
        nebius.common.v1.operation_service_pb2.ListOperationsResponse,
    ]

class InstanceServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Get(
        self,
        request: nebius.compute.v1.instance_service_pb2.GetInstanceRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.compute.v1.instance_pb2.Instance, collections.abc.Awaitable[nebius.compute.v1.instance_pb2.Instance]]: ...

    @abc.abstractmethod
    def GetByName(
        self,
        request: nebius.common.v1.metadata_pb2.GetByNameRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.compute.v1.instance_pb2.Instance, collections.abc.Awaitable[nebius.compute.v1.instance_pb2.Instance]]: ...

    @abc.abstractmethod
    def List(
        self,
        request: nebius.compute.v1.instance_service_pb2.ListInstancesRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.compute.v1.instance_service_pb2.ListInstancesResponse, collections.abc.Awaitable[nebius.compute.v1.instance_service_pb2.ListInstancesResponse]]: ...

    @abc.abstractmethod
    def Create(
        self,
        request: nebius.compute.v1.instance_service_pb2.CreateInstanceRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.common.v1.operation_pb2.Operation, collections.abc.Awaitable[nebius.common.v1.operation_pb2.Operation]]: ...

    @abc.abstractmethod
    def Update(
        self,
        request: nebius.compute.v1.instance_service_pb2.UpdateInstanceRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.common.v1.operation_pb2.Operation, collections.abc.Awaitable[nebius.common.v1.operation_pb2.Operation]]: ...

    @abc.abstractmethod
    def Delete(
        self,
        request: nebius.compute.v1.instance_service_pb2.DeleteInstanceRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.common.v1.operation_pb2.Operation, collections.abc.Awaitable[nebius.common.v1.operation_pb2.Operation]]: ...

    @abc.abstractmethod
    def Start(
        self,
        request: nebius.compute.v1.instance_service_pb2.StartInstanceRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.common.v1.operation_pb2.Operation, collections.abc.Awaitable[nebius.common.v1.operation_pb2.Operation]]: ...

    @abc.abstractmethod
    def Stop(
        self,
        request: nebius.compute.v1.instance_service_pb2.StopInstanceRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.common.v1.operation_pb2.Operation, collections.abc.Awaitable[nebius.common.v1.operation_pb2.Operation]]: ...

    @abc.abstractmethod
    def ListOperationsByParent(
        self,
        request: nebius.compute.v1.operation_service_pb2.ListOperationsByParentRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.common.v1.operation_service_pb2.ListOperationsResponse, collections.abc.Awaitable[nebius.common.v1.operation_service_pb2.ListOperationsResponse]]: ...

def add_InstanceServiceServicer_to_server(servicer: InstanceServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
