"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class NetworkInterfaceSpec(google.protobuf.message.Message):
    """Describes the specification of a network interface."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBNET_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    IP_ADDRESS_FIELD_NUMBER: builtins.int
    PUBLIC_IP_ADDRESS_FIELD_NUMBER: builtins.int
    subnet_id: builtins.str
    """Subnet ID"""
    name: builtins.str
    """Name for interface.
    Must be unique within instance's network interfaces
    """
    @property
    def ip_address(self) -> global___IPAddress:
        """Private IPv4 address associated with the interface."""

    @property
    def public_ip_address(self) -> global___PublicIPAddress:
        """Public IPv4 address associated with the interface."""

    def __init__(
        self,
        *,
        subnet_id: builtins.str = ...,
        name: builtins.str = ...,
        ip_address: global___IPAddress | None = ...,
        public_ip_address: global___PublicIPAddress | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ip_address", b"ip_address", "public_ip_address", b"public_ip_address"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ip_address", b"ip_address", "name", b"name", "public_ip_address", b"public_ip_address", "subnet_id", b"subnet_id"]) -> None: ...

global___NetworkInterfaceSpec = NetworkInterfaceSpec

@typing.final
class IPAddress(google.protobuf.message.Message):
    """Describes an IPv4 address."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALLOCATION_ID_FIELD_NUMBER: builtins.int
    allocation_id: builtins.str
    """Allocation identifier if it was created before."""
    def __init__(
        self,
        *,
        allocation_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["allocation_id", b"allocation_id"]) -> None: ...

global___IPAddress = IPAddress

@typing.final
class PublicIPAddress(google.protobuf.message.Message):
    """Describes a public IP address."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALLOCATION_ID_FIELD_NUMBER: builtins.int
    STATIC_FIELD_NUMBER: builtins.int
    allocation_id: builtins.str
    """Allocation identifier if it was created before."""
    static: builtins.bool
    """If false - Allocation will be created/deleted during NetworkInterface.Allocate/NetworkInterface.Deallocate
    If true  - Allocation will be created/deleted during NetworkInterface.Create/NetworkInterface.Delete
    False by default
    """
    def __init__(
        self,
        *,
        allocation_id: builtins.str = ...,
        static: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["allocation", b"allocation", "allocation_id", b"allocation_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["allocation", b"allocation", "allocation_id", b"allocation_id", "static", b"static"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["allocation", b"allocation"]) -> typing.Literal["allocation_id"] | None: ...

global___PublicIPAddress = PublicIPAddress

@typing.final
class NetworkInterfaceStatus(google.protobuf.message.Message):
    """Describes the status of a network interface."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INDEX_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    IP_ADDRESS_FIELD_NUMBER: builtins.int
    PUBLIC_IP_ADDRESS_FIELD_NUMBER: builtins.int
    MAC_ADDRESS_FIELD_NUMBER: builtins.int
    index: builtins.int
    """The index of the network interface"""
    name: builtins.str
    """Name for interface.
    Unique within instance's network interfaces
    """
    mac_address: builtins.str
    """MAC address"""
    @property
    def ip_address(self) -> global___IPAddressStatus:
        """Effective Private IPv4 address"""

    @property
    def public_ip_address(self) -> global___PublicIPAddressStatus:
        """Effective Public IPv4 address"""

    def __init__(
        self,
        *,
        index: builtins.int = ...,
        name: builtins.str = ...,
        ip_address: global___IPAddressStatus | None = ...,
        public_ip_address: global___PublicIPAddressStatus | None = ...,
        mac_address: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ip_address", b"ip_address", "public_ip_address", b"public_ip_address"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["index", b"index", "ip_address", b"ip_address", "mac_address", b"mac_address", "name", b"name", "public_ip_address", b"public_ip_address"]) -> None: ...

global___NetworkInterfaceStatus = NetworkInterfaceStatus

@typing.final
class IPAddressStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    ALLOCATION_ID_FIELD_NUMBER: builtins.int
    address: builtins.str
    """Effective private IPv4 address assigned to the interface."""
    allocation_id: builtins.str
    """Allocation identifier."""
    def __init__(
        self,
        *,
        address: builtins.str = ...,
        allocation_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "allocation_id", b"allocation_id"]) -> None: ...

global___IPAddressStatus = IPAddressStatus

@typing.final
class PublicIPAddressStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    ALLOCATION_ID_FIELD_NUMBER: builtins.int
    address: builtins.str
    """Effective public IPv4 address assigned to the interface."""
    allocation_id: builtins.str
    """Allocation identifier."""
    def __init__(
        self,
        *,
        address: builtins.str = ...,
        allocation_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "allocation_id", b"allocation_id"]) -> None: ...

global___PublicIPAddressStatus = PublicIPAddressStatus
