"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import nebius.vpc.v1.network_pb2
import nebius.vpc.v1.network_service_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class NetworkServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Get: grpc.UnaryUnaryMultiCallable[
        nebius.vpc.v1.network_service_pb2.GetNetworkRequest,
        nebius.vpc.v1.network_pb2.Network,
    ]

    GetByName: grpc.UnaryUnaryMultiCallable[
        nebius.vpc.v1.network_service_pb2.GetNetworkByNameRequest,
        nebius.vpc.v1.network_pb2.Network,
    ]

    List: grpc.UnaryUnaryMultiCallable[
        nebius.vpc.v1.network_service_pb2.ListNetworksRequest,
        nebius.vpc.v1.network_service_pb2.ListNetworksResponse,
    ]

class NetworkServiceAsyncStub:
    Get: grpc.aio.UnaryUnaryMultiCallable[
        nebius.vpc.v1.network_service_pb2.GetNetworkRequest,
        nebius.vpc.v1.network_pb2.Network,
    ]

    GetByName: grpc.aio.UnaryUnaryMultiCallable[
        nebius.vpc.v1.network_service_pb2.GetNetworkByNameRequest,
        nebius.vpc.v1.network_pb2.Network,
    ]

    List: grpc.aio.UnaryUnaryMultiCallable[
        nebius.vpc.v1.network_service_pb2.ListNetworksRequest,
        nebius.vpc.v1.network_service_pb2.ListNetworksResponse,
    ]

class NetworkServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Get(
        self,
        request: nebius.vpc.v1.network_service_pb2.GetNetworkRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.vpc.v1.network_pb2.Network, collections.abc.Awaitable[nebius.vpc.v1.network_pb2.Network]]: ...

    @abc.abstractmethod
    def GetByName(
        self,
        request: nebius.vpc.v1.network_service_pb2.GetNetworkByNameRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.vpc.v1.network_pb2.Network, collections.abc.Awaitable[nebius.vpc.v1.network_pb2.Network]]: ...

    @abc.abstractmethod
    def List(
        self,
        request: nebius.vpc.v1.network_service_pb2.ListNetworksRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.vpc.v1.network_service_pb2.ListNetworksResponse, collections.abc.Awaitable[nebius.vpc.v1.network_service_pb2.ListNetworksResponse]]: ...

def add_NetworkServiceServicer_to_server(servicer: NetworkServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
