"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import nebius.common.v1.operation_pb2
import nebius.vpc.v1.pool_pb2
import nebius.vpc.v1.pool_service_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class PoolServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Get: grpc.UnaryUnaryMultiCallable[
        nebius.vpc.v1.pool_service_pb2.GetPoolRequest,
        nebius.vpc.v1.pool_pb2.Pool,
    ]

    GetByName: grpc.UnaryUnaryMultiCallable[
        nebius.vpc.v1.pool_service_pb2.GetPoolByNameRequest,
        nebius.vpc.v1.pool_pb2.Pool,
    ]

    List: grpc.UnaryUnaryMultiCallable[
        nebius.vpc.v1.pool_service_pb2.ListPoolsRequest,
        nebius.vpc.v1.pool_service_pb2.ListPoolsResponse,
    ]

    Update: grpc.UnaryUnaryMultiCallable[
        nebius.vpc.v1.pool_service_pb2.UpdatePoolRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

class PoolServiceAsyncStub:
    Get: grpc.aio.UnaryUnaryMultiCallable[
        nebius.vpc.v1.pool_service_pb2.GetPoolRequest,
        nebius.vpc.v1.pool_pb2.Pool,
    ]

    GetByName: grpc.aio.UnaryUnaryMultiCallable[
        nebius.vpc.v1.pool_service_pb2.GetPoolByNameRequest,
        nebius.vpc.v1.pool_pb2.Pool,
    ]

    List: grpc.aio.UnaryUnaryMultiCallable[
        nebius.vpc.v1.pool_service_pb2.ListPoolsRequest,
        nebius.vpc.v1.pool_service_pb2.ListPoolsResponse,
    ]

    Update: grpc.aio.UnaryUnaryMultiCallable[
        nebius.vpc.v1.pool_service_pb2.UpdatePoolRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

class PoolServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Get(
        self,
        request: nebius.vpc.v1.pool_service_pb2.GetPoolRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.vpc.v1.pool_pb2.Pool, collections.abc.Awaitable[nebius.vpc.v1.pool_pb2.Pool]]: ...

    @abc.abstractmethod
    def GetByName(
        self,
        request: nebius.vpc.v1.pool_service_pb2.GetPoolByNameRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.vpc.v1.pool_pb2.Pool, collections.abc.Awaitable[nebius.vpc.v1.pool_pb2.Pool]]: ...

    @abc.abstractmethod
    def List(
        self,
        request: nebius.vpc.v1.pool_service_pb2.ListPoolsRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.vpc.v1.pool_service_pb2.ListPoolsResponse, collections.abc.Awaitable[nebius.vpc.v1.pool_service_pb2.ListPoolsResponse]]: ...

    @abc.abstractmethod
    def Update(
        self,
        request: nebius.vpc.v1.pool_service_pb2.UpdatePoolRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.common.v1.operation_pb2.Operation, collections.abc.Awaitable[nebius.common.v1.operation_pb2.Operation]]: ...

def add_PoolServiceServicer_to_server(servicer: PoolServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
