# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nebius/common/v1/metadata.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from nebius import annotations_pb2 as nebius_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fnebius/common/v1/metadata.proto\x12\x10nebius.common.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18nebius/annotations.proto\"\xcb\x02\n\x10ResourceMetadata\x12\x10\n\x02id\x18\x01 \x01(\tB\x04\xbaJ\x01\x03\x12\x19\n\tparent_id\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01\x12\x0c\n\x04name\x18\x03 \x01(\t\x12!\n\x10resource_version\x18\x04 \x01(\x03\x42\x07\xbaH\x04\"\x02(\x00\x12\x34\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x04\xbaJ\x01\x05\x12\x34\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x04\xbaJ\x01\x05\x12>\n\x06labels\x18\x07 \x03(\x0b\x32..nebius.common.v1.ResourceMetadata.LabelsEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"3\n\x10GetByNameRequest\x12\x11\n\tparent_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\tBZ\n\x17\x61i.nebius.pub.common.v1B\rMetadataProtoP\x01Z.github.com/nebius/gosdk/proto/nebius/common/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nebius.common.v1.metadata_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027ai.nebius.pub.common.v1B\rMetadataProtoP\001Z.github.com/nebius/gosdk/proto/nebius/common/v1'
  _RESOURCEMETADATA_LABELSENTRY._options = None
  _RESOURCEMETADATA_LABELSENTRY._serialized_options = b'8\001'
  _RESOURCEMETADATA.fields_by_name['id']._options = None
  _RESOURCEMETADATA.fields_by_name['id']._serialized_options = b'\272J\001\003'
  _RESOURCEMETADATA.fields_by_name['parent_id']._options = None
  _RESOURCEMETADATA.fields_by_name['parent_id']._serialized_options = b'\272H\003\310\001\001'
  _RESOURCEMETADATA.fields_by_name['resource_version']._options = None
  _RESOURCEMETADATA.fields_by_name['resource_version']._serialized_options = b'\272H\004\"\002(\000'
  _RESOURCEMETADATA.fields_by_name['created_at']._options = None
  _RESOURCEMETADATA.fields_by_name['created_at']._serialized_options = b'\272J\001\005'
  _RESOURCEMETADATA.fields_by_name['updated_at']._options = None
  _RESOURCEMETADATA.fields_by_name['updated_at']._serialized_options = b'\272J\001\005'
  _globals['_RESOURCEMETADATA']._serialized_start=142
  _globals['_RESOURCEMETADATA']._serialized_end=473
  _globals['_RESOURCEMETADATA_LABELSENTRY']._serialized_start=428
  _globals['_RESOURCEMETADATA_LABELSENTRY']._serialized_end=473
  _globals['_GETBYNAMEREQUEST']._serialized_start=475
  _globals['_GETBYNAMEREQUEST']._serialized_end=526
# @@protoc_insertion_point(module_scope)
