"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import nebius.common.v1.operation_pb2
import nebius.registry.v1.artifact_pb2
import nebius.registry.v1.artifact_service_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class ArtifactServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Get: grpc.UnaryUnaryMultiCallable[
        nebius.registry.v1.artifact_service_pb2.GetArtifactRequest,
        nebius.registry.v1.artifact_pb2.Artifact,
    ]

    List: grpc.UnaryUnaryMultiCallable[
        nebius.registry.v1.artifact_service_pb2.ListArtifactsRequest,
        nebius.registry.v1.artifact_service_pb2.ListArtifactsResponse,
    ]

    Delete: grpc.UnaryUnaryMultiCallable[
        nebius.registry.v1.artifact_service_pb2.DeleteArtifactRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

class ArtifactServiceAsyncStub:
    Get: grpc.aio.UnaryUnaryMultiCallable[
        nebius.registry.v1.artifact_service_pb2.GetArtifactRequest,
        nebius.registry.v1.artifact_pb2.Artifact,
    ]

    List: grpc.aio.UnaryUnaryMultiCallable[
        nebius.registry.v1.artifact_service_pb2.ListArtifactsRequest,
        nebius.registry.v1.artifact_service_pb2.ListArtifactsResponse,
    ]

    Delete: grpc.aio.UnaryUnaryMultiCallable[
        nebius.registry.v1.artifact_service_pb2.DeleteArtifactRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

class ArtifactServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Get(
        self,
        request: nebius.registry.v1.artifact_service_pb2.GetArtifactRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.registry.v1.artifact_pb2.Artifact, collections.abc.Awaitable[nebius.registry.v1.artifact_pb2.Artifact]]: ...

    @abc.abstractmethod
    def List(
        self,
        request: nebius.registry.v1.artifact_service_pb2.ListArtifactsRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.registry.v1.artifact_service_pb2.ListArtifactsResponse, collections.abc.Awaitable[nebius.registry.v1.artifact_service_pb2.ListArtifactsResponse]]: ...

    @abc.abstractmethod
    def Delete(
        self,
        request: nebius.registry.v1.artifact_service_pb2.DeleteArtifactRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.common.v1.operation_pb2.Operation, collections.abc.Awaitable[nebius.common.v1.operation_pb2.Operation]]: ...

def add_ArtifactServiceServicer_to_server(servicer: ArtifactServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
