# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nebius/registry/v1/registry_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from nebius.common.v1 import metadata_pb2 as nebius_dot_common_dot_v1_dot_metadata__pb2
from nebius.common.v1 import operation_pb2 as nebius_dot_common_dot_v1_dot_operation__pb2
from nebius.registry.v1 import registry_pb2 as nebius_dot_registry_dot_v1_dot_registry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)nebius/registry/v1/registry_service.proto\x12\x12nebius.registry.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x1fnebius/common/v1/metadata.proto\x1a nebius/common/v1/operation.proto\x1a!nebius/registry/v1/registry.proto\"(\n\x12GetRegistryRequest\x12\x12\n\x02id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01\"a\n\x15ListRegistriesRequest\x12\x11\n\tparent_id\x18\x01 \x01(\t\x12\x11\n\tpage_size\x18\x02 \x01(\x03\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x0e\n\x06\x66ilter\x18\x04 \x01(\t\"^\n\x16ListRegistriesResponse\x12+\n\x05items\x18\x01 \x03(\x0b\x32\x1c.nebius.registry.v1.Registry\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\"}\n\x15\x43reateRegistryRequest\x12\x34\n\x08metadata\x18\x01 \x01(\x0b\x32\".nebius.common.v1.ResourceMetadata\x12.\n\x04spec\x18\x02 \x01(\x0b\x32 .nebius.registry.v1.RegistrySpec\"}\n\x15UpdateRegistryRequest\x12\x34\n\x08metadata\x18\x01 \x01(\x0b\x32\".nebius.common.v1.ResourceMetadata\x12.\n\x04spec\x18\x02 \x01(\x0b\x32 .nebius.registry.v1.RegistrySpec\"+\n\x15\x44\x65leteRegistryRequest\x12\x12\n\x02id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01\x32\xb3\x03\n\x0fRegistryService\x12K\n\x03Get\x12&.nebius.registry.v1.GetRegistryRequest\x1a\x1c.nebius.registry.v1.Registry\x12]\n\x04List\x12).nebius.registry.v1.ListRegistriesRequest\x1a*.nebius.registry.v1.ListRegistriesResponse\x12P\n\x06\x43reate\x12).nebius.registry.v1.CreateRegistryRequest\x1a\x1b.nebius.common.v1.Operation\x12P\n\x06Update\x12).nebius.registry.v1.UpdateRegistryRequest\x1a\x1b.nebius.common.v1.Operation\x12P\n\x06\x44\x65lete\x12).nebius.registry.v1.DeleteRegistryRequest\x1a\x1b.nebius.common.v1.OperationBe\n\x19\x61i.nebius.pub.registry.v1B\x14RegistryServiceProtoP\x01Z0github.com/nebius/gosdk/proto/nebius/registry/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nebius.registry.v1.registry_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031ai.nebius.pub.registry.v1B\024RegistryServiceProtoP\001Z0github.com/nebius/gosdk/proto/nebius/registry/v1'
  _GETREGISTRYREQUEST.fields_by_name['id']._options = None
  _GETREGISTRYREQUEST.fields_by_name['id']._serialized_options = b'\272H\003\310\001\001'
  _DELETEREGISTRYREQUEST.fields_by_name['id']._options = None
  _DELETEREGISTRYREQUEST.fields_by_name['id']._serialized_options = b'\272H\003\310\001\001'
  _globals['_GETREGISTRYREQUEST']._serialized_start=196
  _globals['_GETREGISTRYREQUEST']._serialized_end=236
  _globals['_LISTREGISTRIESREQUEST']._serialized_start=238
  _globals['_LISTREGISTRIESREQUEST']._serialized_end=335
  _globals['_LISTREGISTRIESRESPONSE']._serialized_start=337
  _globals['_LISTREGISTRIESRESPONSE']._serialized_end=431
  _globals['_CREATEREGISTRYREQUEST']._serialized_start=433
  _globals['_CREATEREGISTRYREQUEST']._serialized_end=558
  _globals['_UPDATEREGISTRYREQUEST']._serialized_start=560
  _globals['_UPDATEREGISTRYREQUEST']._serialized_end=685
  _globals['_DELETEREGISTRYREQUEST']._serialized_start=687
  _globals['_DELETEREGISTRYREQUEST']._serialized_end=730
  _globals['_REGISTRYSERVICE']._serialized_start=733
  _globals['_REGISTRYSERVICE']._serialized_end=1168
# @@protoc_insertion_point(module_scope)
