"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import nebius.common.v1.metadata_pb2
import nebius.common.v1.operation_pb2
import nebius.mk8s.v1.cluster_pb2
import nebius.mk8s.v1.cluster_service_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class ClusterServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Get: grpc.UnaryUnaryMultiCallable[
        nebius.mk8s.v1.cluster_service_pb2.GetClusterRequest,
        nebius.mk8s.v1.cluster_pb2.Cluster,
    ]

    GetByName: grpc.UnaryUnaryMultiCallable[
        nebius.common.v1.metadata_pb2.GetByNameRequest,
        nebius.mk8s.v1.cluster_pb2.Cluster,
    ]

    List: grpc.UnaryUnaryMultiCallable[
        nebius.mk8s.v1.cluster_service_pb2.ListClustersRequest,
        nebius.mk8s.v1.cluster_service_pb2.ListClustersResponse,
    ]

    Create: grpc.UnaryUnaryMultiCallable[
        nebius.mk8s.v1.cluster_service_pb2.CreateClusterRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

    Update: grpc.UnaryUnaryMultiCallable[
        nebius.mk8s.v1.cluster_service_pb2.UpdateClusterRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

    Delete: grpc.UnaryUnaryMultiCallable[
        nebius.mk8s.v1.cluster_service_pb2.DeleteClusterRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

class ClusterServiceAsyncStub:
    Get: grpc.aio.UnaryUnaryMultiCallable[
        nebius.mk8s.v1.cluster_service_pb2.GetClusterRequest,
        nebius.mk8s.v1.cluster_pb2.Cluster,
    ]

    GetByName: grpc.aio.UnaryUnaryMultiCallable[
        nebius.common.v1.metadata_pb2.GetByNameRequest,
        nebius.mk8s.v1.cluster_pb2.Cluster,
    ]

    List: grpc.aio.UnaryUnaryMultiCallable[
        nebius.mk8s.v1.cluster_service_pb2.ListClustersRequest,
        nebius.mk8s.v1.cluster_service_pb2.ListClustersResponse,
    ]

    Create: grpc.aio.UnaryUnaryMultiCallable[
        nebius.mk8s.v1.cluster_service_pb2.CreateClusterRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

    Update: grpc.aio.UnaryUnaryMultiCallable[
        nebius.mk8s.v1.cluster_service_pb2.UpdateClusterRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

    Delete: grpc.aio.UnaryUnaryMultiCallable[
        nebius.mk8s.v1.cluster_service_pb2.DeleteClusterRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

class ClusterServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Get(
        self,
        request: nebius.mk8s.v1.cluster_service_pb2.GetClusterRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.mk8s.v1.cluster_pb2.Cluster, collections.abc.Awaitable[nebius.mk8s.v1.cluster_pb2.Cluster]]: ...

    @abc.abstractmethod
    def GetByName(
        self,
        request: nebius.common.v1.metadata_pb2.GetByNameRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.mk8s.v1.cluster_pb2.Cluster, collections.abc.Awaitable[nebius.mk8s.v1.cluster_pb2.Cluster]]: ...

    @abc.abstractmethod
    def List(
        self,
        request: nebius.mk8s.v1.cluster_service_pb2.ListClustersRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.mk8s.v1.cluster_service_pb2.ListClustersResponse, collections.abc.Awaitable[nebius.mk8s.v1.cluster_service_pb2.ListClustersResponse]]: ...

    @abc.abstractmethod
    def Create(
        self,
        request: nebius.mk8s.v1.cluster_service_pb2.CreateClusterRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.common.v1.operation_pb2.Operation, collections.abc.Awaitable[nebius.common.v1.operation_pb2.Operation]]: ...

    @abc.abstractmethod
    def Update(
        self,
        request: nebius.mk8s.v1.cluster_service_pb2.UpdateClusterRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.common.v1.operation_pb2.Operation, collections.abc.Awaitable[nebius.common.v1.operation_pb2.Operation]]: ...

    @abc.abstractmethod
    def Delete(
        self,
        request: nebius.mk8s.v1.cluster_service_pb2.DeleteClusterRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.common.v1.operation_pb2.Operation, collections.abc.Awaitable[nebius.common.v1.operation_pb2.Operation]]: ...

def add_ClusterServiceServicer_to_server(servicer: ClusterServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
