"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import nebius.common.v1.metadata_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Cluster(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METADATA_FIELD_NUMBER: builtins.int
    SPEC_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    @property
    def metadata(self) -> nebius.common.v1.metadata_pb2.ResourceMetadata: ...
    @property
    def spec(self) -> global___ClusterSpec: ...
    @property
    def status(self) -> global___ClusterStatus: ...
    def __init__(
        self,
        *,
        metadata: nebius.common.v1.metadata_pb2.ResourceMetadata | None = ...,
        spec: global___ClusterSpec | None = ...,
        status: global___ClusterStatus | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["metadata", b"metadata", "spec", b"spec", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["metadata", b"metadata", "spec", b"spec", "status", b"status"]) -> None: ...

global___Cluster = Cluster

@typing.final
class ClusterSpec(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTROL_PLANE_FIELD_NUMBER: builtins.int
    @property
    def control_plane(self) -> global___ControlPlaneSpec: ...
    def __init__(
        self,
        *,
        control_plane: global___ControlPlaneSpec | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["control_plane", b"control_plane"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["control_plane", b"control_plane"]) -> None: ...

global___ClusterSpec = ClusterSpec

@typing.final
class ControlPlaneSpec(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    SUBNET_ID_FIELD_NUMBER: builtins.int
    ENDPOINTS_FIELD_NUMBER: builtins.int
    ETCD_CLUSTER_SIZE_FIELD_NUMBER: builtins.int
    version: builtins.str
    """Version is desired Kubernetes version of the cluster. For now only acceptable format is
    `MAJOR.MINOR` like "1.30". Option for patch version update will be added later.
    """
    subnet_id: builtins.str
    """Subnet ID where control plane instances will be located."""
    etcd_cluster_size: builtins.int
    @property
    def endpoints(self) -> global___ControlPlaneEndpointsSpec: ...
    def __init__(
        self,
        *,
        version: builtins.str = ...,
        subnet_id: builtins.str = ...,
        endpoints: global___ControlPlaneEndpointsSpec | None = ...,
        etcd_cluster_size: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["endpoints", b"endpoints"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["endpoints", b"endpoints", "etcd_cluster_size", b"etcd_cluster_size", "subnet_id", b"subnet_id", "version", b"version"]) -> None: ...

global___ControlPlaneSpec = ControlPlaneSpec

@typing.final
class ControlPlaneEndpointsSpec(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUBLIC_ENDPOINT_FIELD_NUMBER: builtins.int
    @property
    def public_endpoint(self) -> global___PublicEndpointSpec:
        """PublicEndpointSpec is a specification of public endpoint for control plane."""

    def __init__(
        self,
        *,
        public_endpoint: global___PublicEndpointSpec | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["public_endpoint", b"public_endpoint"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["public_endpoint", b"public_endpoint"]) -> None: ...

global___ControlPlaneEndpointsSpec = ControlPlaneEndpointsSpec

@typing.final
class PublicEndpointSpec(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___PublicEndpointSpec = PublicEndpointSpec

@typing.final
class ClusterStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _State:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ClusterStatus._State.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        STATE_UNSPECIFIED: ClusterStatus._State.ValueType  # 0
        PROVISIONING: ClusterStatus._State.ValueType  # 1
        RUNNING: ClusterStatus._State.ValueType  # 2
        DELETING: ClusterStatus._State.ValueType  # 3

    class State(_State, metaclass=_StateEnumTypeWrapper): ...
    STATE_UNSPECIFIED: ClusterStatus.State.ValueType  # 0
    PROVISIONING: ClusterStatus.State.ValueType  # 1
    RUNNING: ClusterStatus.State.ValueType  # 2
    DELETING: ClusterStatus.State.ValueType  # 3

    STATE_FIELD_NUMBER: builtins.int
    CONTROL_PLANE_FIELD_NUMBER: builtins.int
    RECONCILING_FIELD_NUMBER: builtins.int
    state: global___ClusterStatus.State.ValueType
    reconciling: builtins.bool
    """Show that changes are in flight"""
    @property
    def control_plane(self) -> global___ControlPlaneStatus: ...
    def __init__(
        self,
        *,
        state: global___ClusterStatus.State.ValueType = ...,
        control_plane: global___ControlPlaneStatus | None = ...,
        reconciling: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["control_plane", b"control_plane"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["control_plane", b"control_plane", "reconciling", b"reconciling", "state", b"state"]) -> None: ...

global___ClusterStatus = ClusterStatus

@typing.final
class ControlPlaneStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    ENDPOINTS_FIELD_NUMBER: builtins.int
    AUTH_FIELD_NUMBER: builtins.int
    version: builtins.str
    """Version have format `major.minor.patch-nebius-cp.n` like "1.30.0-nebius-cp.3"."""
    @property
    def endpoints(self) -> global___ControlPlaneStatusEndpoints: ...
    @property
    def auth(self) -> global___ControlPlaneStatusAuth: ...
    def __init__(
        self,
        *,
        version: builtins.str = ...,
        endpoints: global___ControlPlaneStatusEndpoints | None = ...,
        auth: global___ControlPlaneStatusAuth | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["auth", b"auth", "endpoints", b"endpoints"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["auth", b"auth", "endpoints", b"endpoints", "version", b"version"]) -> None: ...

global___ControlPlaneStatus = ControlPlaneStatus

@typing.final
class ControlPlaneStatusEndpoints(google.protobuf.message.Message):
    """Endpoints of Kubernetes control plane. Kubernetes API can be accessed at `https://endpoint/`."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUBLIC_ENDPOINT_FIELD_NUMBER: builtins.int
    PRIVATE_ENDPOINT_FIELD_NUMBER: builtins.int
    public_endpoint: builtins.str
    """DNS name or IP address accessible from the Internet."""
    private_endpoint: builtins.str
    """DNS name or IP address accessible from the user VPC."""
    def __init__(
        self,
        *,
        public_endpoint: builtins.str = ...,
        private_endpoint: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["private_endpoint", b"private_endpoint", "public_endpoint", b"public_endpoint"]) -> None: ...

global___ControlPlaneStatusEndpoints = ControlPlaneStatusEndpoints

@typing.final
class ControlPlaneStatusAuth(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLUSTER_CA_CERTIFICATE_FIELD_NUMBER: builtins.int
    cluster_ca_certificate: builtins.str
    def __init__(
        self,
        *,
        cluster_ca_certificate: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cluster_ca_certificate", b"cluster_ca_certificate"]) -> None: ...

global___ControlPlaneStatusAuth = ControlPlaneStatusAuth
