# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nebius/mk8s/v1/instance_template.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from nebius import annotations_pb2 as nebius_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&nebius/mk8s/v1/instance_template.proto\x12\x0enebius.mk8s.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x18nebius/annotations.proto\"\xa4\x02\n\x08\x44iskSpec\x12\x14\n\nsize_bytes\x18\x01 \x01(\x03H\x00\x12\x18\n\x0esize_kibibytes\x18\x02 \x01(\x03H\x00\x12\x18\n\x0esize_mebibytes\x18\x03 \x01(\x03H\x00\x12\x18\n\x0esize_gibibytes\x18\x04 \x01(\x03H\x00\x12\x18\n\x10\x62lock_size_bytes\x18\x05 \x01(\x03\x12\x35\n\x04type\x18\x06 \x01(\x0e\x32!.nebius.mk8s.v1.DiskSpec.DiskTypeB\x04\xbaJ\x01\x07\"T\n\x08\x44iskType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0f\n\x0bNETWORK_SSD\x10\x01\x12\x0f\n\x0bNETWORK_HDD\x10\x02\x12\x15\n\x11NETWORK_SSD_IO_M3\x10\x03\x42\r\n\x04size\x12\x05\xbaH\x02\x08\x01\"J\n\rResourcesSpec\x12\x18\n\x08platform\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01\x12\x10\n\x06preset\x18\x02 \x01(\tH\x00\x42\r\n\x04size\x12\x05\xbaH\x02\x08\x01\x42^\n\x15\x61i.nebius.pub.mk8s.v1B\x15InstanceTemplateProtoP\x01Z,github.com/nebius/gosdk/proto/nebius/mk8s/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nebius.mk8s.v1.instance_template_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025ai.nebius.pub.mk8s.v1B\025InstanceTemplateProtoP\001Z,github.com/nebius/gosdk/proto/nebius/mk8s/v1'
  _DISKSPEC.oneofs_by_name['size']._options = None
  _DISKSPEC.oneofs_by_name['size']._serialized_options = b'\272H\002\010\001'
  _DISKSPEC.fields_by_name['type']._options = None
  _DISKSPEC.fields_by_name['type']._serialized_options = b'\272J\001\007'
  _RESOURCESSPEC.oneofs_by_name['size']._options = None
  _RESOURCESSPEC.oneofs_by_name['size']._serialized_options = b'\272H\002\010\001'
  _RESOURCESSPEC.fields_by_name['platform']._options = None
  _RESOURCESSPEC.fields_by_name['platform']._serialized_options = b'\272H\003\310\001\001'
  _globals['_DISKSPEC']._serialized_start=114
  _globals['_DISKSPEC']._serialized_end=406
  _globals['_DISKSPEC_DISKTYPE']._serialized_start=307
  _globals['_DISKSPEC_DISKTYPE']._serialized_end=391
  _globals['_RESOURCESSPEC']._serialized_start=408
  _globals['_RESOURCESSPEC']._serialized_end=482
# @@protoc_insertion_point(module_scope)
