"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.descriptor_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.internal.extension_dict
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ResourceBehavior:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ResourceBehaviorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ResourceBehavior.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RESOURCE_BEHAVIOR_UNSPECIFIED: _ResourceBehavior.ValueType  # 0
    """The behavior of the resource is unspecified.
    Avoid using this default value.
    """
    MOVABLE: _ResourceBehavior.ValueType  # 1
    """Indicates that the resource can be moved to another parent, typically an
    IAM container, though not necessarily limited to this.
    This behavior suggests that the `metadata.parent_id` attribute could be modified.
    """
    UNNAMED: _ResourceBehavior.ValueType  # 2
    """Indicates that the resource name can be unspecified or does not follow
    uniqueness requirement within parent_id and resource type.
    """
    IMMUTABLE_NAME: _ResourceBehavior.ValueType  # 3
    """Indicates that the resource is named, and the name cannot be changed after
    it is created. It is strongly recommended to do srvices with renaming
    capability, as the guidelines suggest.
    """

class ResourceBehavior(_ResourceBehavior, metaclass=_ResourceBehaviorEnumTypeWrapper): ...

RESOURCE_BEHAVIOR_UNSPECIFIED: ResourceBehavior.ValueType  # 0
"""The behavior of the resource is unspecified.
Avoid using this default value.
"""
MOVABLE: ResourceBehavior.ValueType  # 1
"""Indicates that the resource can be moved to another parent, typically an
IAM container, though not necessarily limited to this.
This behavior suggests that the `metadata.parent_id` attribute could be modified.
"""
UNNAMED: ResourceBehavior.ValueType  # 2
"""Indicates that the resource name can be unspecified or does not follow
uniqueness requirement within parent_id and resource type.
"""
IMMUTABLE_NAME: ResourceBehavior.ValueType  # 3
"""Indicates that the resource is named, and the name cannot be changed after
it is created. It is strongly recommended to do srvices with renaming
capability, as the guidelines suggest.
"""
global___ResourceBehavior = ResourceBehavior

class _FieldBehavior:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _FieldBehaviorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_FieldBehavior.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    FIELD_BEHAVIOR_UNSPECIFIED: _FieldBehavior.ValueType  # 0
    IMMUTABLE: _FieldBehavior.ValueType  # 2
    """This indicates that the field can't be changed during a resource update.
    Changing the field value will cause an `INVALID_ARGUMENT` error.
    Resource recreate requires a change of the field value.
    """
    IDENTIFIER: _FieldBehavior.ValueType  # 3
    """Indicates field is a resource ID, so it MUST be present on a resource
    update, but MUST NOT be set on create.
    Otherwise, RPC will fail with the `INVALID_ARGUMENT` error
    """
    INPUT_ONLY: _FieldBehavior.ValueType  # 4
    """Indicates field is not present in output."""
    OUTPUT_ONLY: _FieldBehavior.ValueType  # 5
    """Indicates field can't be set on create or changed on update.
    Otherwise, RPC will fail with the `INVALID_ARGUMENT` error
    """
    MEANINGFUL_EMPTY_VALUE: _FieldBehavior.ValueType  # 6
    """Indicates that an empty message and a null have different semantics.
    Usually, that field is a feature spec message: its empty message enables
    that feature, and null disables it. Such a message is different from `bool`
    because it already has some feature parameters, or they can be added later
    in a backward-compatible way.
    IMPORTANT: if the message itself is recursive, this behavior is forced.
    """
    NON_EMPTY_DEFAULT: _FieldBehavior.ValueType  # 7
    """Indicates that an empty (default) value will be filled by the server.
    Usually, that field is a feature spec value, which by default is computed.
    Values marked with this annotation won't raise error if they are not set
    and the returned value is not equal to protobuf default.
    """

class FieldBehavior(_FieldBehavior, metaclass=_FieldBehaviorEnumTypeWrapper): ...

FIELD_BEHAVIOR_UNSPECIFIED: FieldBehavior.ValueType  # 0
IMMUTABLE: FieldBehavior.ValueType  # 2
"""This indicates that the field can't be changed during a resource update.
Changing the field value will cause an `INVALID_ARGUMENT` error.
Resource recreate requires a change of the field value.
"""
IDENTIFIER: FieldBehavior.ValueType  # 3
"""Indicates field is a resource ID, so it MUST be present on a resource
update, but MUST NOT be set on create.
Otherwise, RPC will fail with the `INVALID_ARGUMENT` error
"""
INPUT_ONLY: FieldBehavior.ValueType  # 4
"""Indicates field is not present in output."""
OUTPUT_ONLY: FieldBehavior.ValueType  # 5
"""Indicates field can't be set on create or changed on update.
Otherwise, RPC will fail with the `INVALID_ARGUMENT` error
"""
MEANINGFUL_EMPTY_VALUE: FieldBehavior.ValueType  # 6
"""Indicates that an empty message and a null have different semantics.
Usually, that field is a feature spec message: its empty message enables
that feature, and null disables it. Such a message is different from `bool`
because it already has some feature parameters, or they can be added later
in a backward-compatible way.
IMPORTANT: if the message itself is recursive, this behavior is forced.
"""
NON_EMPTY_DEFAULT: FieldBehavior.ValueType  # 7
"""Indicates that an empty (default) value will be filled by the server.
Usually, that field is a feature spec value, which by default is computed.
Values marked with this annotation won't raise error if they are not set
and the returned value is not equal to protobuf default.
"""
global___FieldBehavior = FieldBehavior

API_SERVICE_NAME_FIELD_NUMBER: builtins.int
RESOURCE_BEHAVIOR_FIELD_NUMBER: builtins.int
FIELD_BEHAVIOR_FIELD_NUMBER: builtins.int
SENSITIVE_FIELD_NUMBER: builtins.int
ONEOF_BEHAVIOR_FIELD_NUMBER: builtins.int
api_service_name: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.ServiceOptions, builtins.str]
"""by default API tools assume that every service is configured with address
   in a format: <first-part-after-nebius-in-grpc-path>.<domain>
   example: nebius.dns.v1alpha1.ZoneService => dns.<domain>
this option is used to override the default behavior for private api domains
   example for iam access: option (api_service_name) = "access-service.iam";
   that leads to access-service.iam.<domain>
"""
resource_behavior: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.MessageOptions, google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___ResourceBehavior.ValueType]]
field_behavior: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.FieldOptions, google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___FieldBehavior.ValueType]]
"""Field behavior describes how the field behaves on input or output."""
sensitive: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.FieldOptions, builtins.bool]
"""Sensitive field is masked/removed from the message while logging, storing in DB and
on all others persistent layers (except specialized storage like PDS).
"""
oneof_behavior: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.OneofOptions, google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___FieldBehavior.ValueType]]
"""Field behavior describes how oneof behaves on input or output."""
