"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _StorageClass:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StorageClassEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_StorageClass.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    STORAGE_CLASS_UNSPECIFIED: _StorageClass.ValueType  # 0
    STANDARD: _StorageClass.ValueType  # 1

class StorageClass(_StorageClass, metaclass=_StorageClassEnumTypeWrapper): ...

STORAGE_CLASS_UNSPECIFIED: StorageClass.ValueType  # 0
STANDARD: StorageClass.ValueType  # 1
global___StorageClass = StorageClass

class _VersioningPolicy:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _VersioningPolicyEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_VersioningPolicy.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    VERSIONING_POLICY_UNSPECIFIED: _VersioningPolicy.ValueType  # 0
    DISABLED: _VersioningPolicy.ValueType  # 1
    ENABLED: _VersioningPolicy.ValueType  # 2
    SUSPENDED: _VersioningPolicy.ValueType  # 3

class VersioningPolicy(_VersioningPolicy, metaclass=_VersioningPolicyEnumTypeWrapper): ...

VERSIONING_POLICY_UNSPECIFIED: VersioningPolicy.ValueType  # 0
DISABLED: VersioningPolicy.ValueType  # 1
ENABLED: VersioningPolicy.ValueType  # 2
SUSPENDED: VersioningPolicy.ValueType  # 3
global___VersioningPolicy = VersioningPolicy
