# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nebius/storage/v1/bucket_counters.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nebius.storage.v1 import base_pb2 as nebius_dot_storage_dot_v1_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'nebius/storage/v1/bucket_counters.proto\x12\x11nebius.storage.v1\x1a\x1cnebius/storage/v1/base.proto\"\xfb\x01\n\x15\x43urrentBucketCounters\x12\x1f\n\x17simple_objects_quantity\x18\x01 \x01(\x03\x12\x1b\n\x13simple_objects_size\x18\x02 \x01(\x03\x12\"\n\x1amultipart_objects_quantity\x18\x03 \x01(\x03\x12\x1e\n\x16multipart_objects_size\x18\x04 \x01(\x03\x12\"\n\x1amultipart_uploads_quantity\x18\x05 \x01(\x03\x12\x1f\n\x17inflight_parts_quantity\x18\x06 \x01(\x03\x12\x1b\n\x13inflight_parts_size\x18\x07 \x01(\x03\"\x9c\x01\n\x18NonCurrentBucketCounters\x12\x1f\n\x17simple_objects_quantity\x18\x01 \x01(\x03\x12\x1b\n\x13simple_objects_size\x18\x02 \x01(\x03\x12\"\n\x1amultipart_objects_quantity\x18\x03 \x01(\x03\x12\x1e\n\x16multipart_objects_size\x18\x04 \x01(\x03\"\xcf\x01\n\x0e\x42ucketCounters\x12\x36\n\rstorage_class\x18\x01 \x01(\x0e\x32\x1f.nebius.storage.v1.StorageClass\x12:\n\x08\x63ounters\x18\x02 \x01(\x0b\x32(.nebius.storage.v1.CurrentBucketCounters\x12I\n\x14non_current_counters\x18\x03 \x01(\x0b\x32+.nebius.storage.v1.NonCurrentBucketCountersBb\n\x18\x61i.nebius.pub.storage.v1B\x13\x42ucketCountersProtoP\x01Z/github.com/nebius/gosdk/proto/nebius/storage/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nebius.storage.v1.bucket_counters_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030ai.nebius.pub.storage.v1B\023BucketCountersProtoP\001Z/github.com/nebius/gosdk/proto/nebius/storage/v1'
  _globals['_CURRENTBUCKETCOUNTERS']._serialized_start=93
  _globals['_CURRENTBUCKETCOUNTERS']._serialized_end=344
  _globals['_NONCURRENTBUCKETCOUNTERS']._serialized_start=347
  _globals['_NONCURRENTBUCKETCOUNTERS']._serialized_end=503
  _globals['_BUCKETCOUNTERS']._serialized_start=506
  _globals['_BUCKETCOUNTERS']._serialized_end=713
# @@protoc_insertion_point(module_scope)
