# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nebius/storage/v1/lifecycle.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nebius import annotations_pb2 as nebius_dot_annotations__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!nebius/storage/v1/lifecycle.proto\x12\x11nebius.storage.v1\x1a\x18nebius/annotations.proto\x1a\x1b\x62uf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"I\n\x16LifecycleConfiguration\x12/\n\x05rules\x18\x01 \x03(\x0b\x32 .nebius.storage.v1.LifecycleRule\"\xde\x03\n\rLifecycleRule\x12\x12\n\x02id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01\x12?\n\x06status\x18\x02 \x01(\x0e\x32\'.nebius.storage.v1.LifecycleRule.StatusB\x06\xbaH\x03\xc8\x01\x01\x12\x38\n\x06\x66ilter\x18\x03 \x01(\x0b\x32\".nebius.storage.v1.LifecycleFilterB\x04\xbaJ\x01\x07\x12:\n\nexpiration\x18\x04 \x01(\x0b\x32&.nebius.storage.v1.LifecycleExpiration\x12^\n\x1dnoncurrent_version_expiration\x18\x05 \x01(\x0b\x32\x37.nebius.storage.v1.LifecycleNoncurrentVersionExpiration\x12\x65\n!abort_incomplete_multipart_upload\x18\x06 \x01(\x0b\x32:.nebius.storage.v1.LifecycleAbortIncompleteMultipartUpload\";\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x0b\n\x07\x45NABLED\x10\x01\x12\x0c\n\x08\x44ISABLED\x10\x02\"n\n\x0fLifecycleFilter\x12\x0e\n\x06prefix\x18\x01 \x01(\t\x12&\n\x1eobject_size_greater_than_bytes\x18\x02 \x01(\x03\x12#\n\x1bobject_size_less_than_bytes\x18\x03 \x01(\x03\"\x87\x01\n\x13LifecycleExpiration\x12*\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x12\x0e\n\x04\x64\x61ys\x18\x02 \x01(\x05H\x00\x12$\n\x1c\x65xpired_object_delete_marker\x18\x03 \x01(\x08\x42\x0e\n\x0c\x65xpired_with\"\x85\x01\n$LifecycleNoncurrentVersionExpiration\x12&\n\x19newer_noncurrent_versions\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x17\n\x0fnoncurrent_days\x18\x02 \x01(\x05\x42\x1c\n\x1a_newer_noncurrent_versions\"H\n\'LifecycleAbortIncompleteMultipartUpload\x12\x1d\n\x15\x64\x61ys_after_initiation\x18\x01 \x01(\x05\x42]\n\x18\x61i.nebius.pub.storage.v1B\x0eLifecycleProtoP\x01Z/github.com/nebius/gosdk/proto/nebius/storage/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nebius.storage.v1.lifecycle_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030ai.nebius.pub.storage.v1B\016LifecycleProtoP\001Z/github.com/nebius/gosdk/proto/nebius/storage/v1'
  _LIFECYCLERULE.fields_by_name['id']._options = None
  _LIFECYCLERULE.fields_by_name['id']._serialized_options = b'\272H\003\310\001\001'
  _LIFECYCLERULE.fields_by_name['status']._options = None
  _LIFECYCLERULE.fields_by_name['status']._serialized_options = b'\272H\003\310\001\001'
  _LIFECYCLERULE.fields_by_name['filter']._options = None
  _LIFECYCLERULE.fields_by_name['filter']._serialized_options = b'\272J\001\007'
  _globals['_LIFECYCLECONFIGURATION']._serialized_start=144
  _globals['_LIFECYCLECONFIGURATION']._serialized_end=217
  _globals['_LIFECYCLERULE']._serialized_start=220
  _globals['_LIFECYCLERULE']._serialized_end=698
  _globals['_LIFECYCLERULE_STATUS']._serialized_start=639
  _globals['_LIFECYCLERULE_STATUS']._serialized_end=698
  _globals['_LIFECYCLEFILTER']._serialized_start=700
  _globals['_LIFECYCLEFILTER']._serialized_end=810
  _globals['_LIFECYCLEEXPIRATION']._serialized_start=813
  _globals['_LIFECYCLEEXPIRATION']._serialized_end=948
  _globals['_LIFECYCLENONCURRENTVERSIONEXPIRATION']._serialized_start=951
  _globals['_LIFECYCLENONCURRENTVERSIONEXPIRATION']._serialized_end=1084
  _globals['_LIFECYCLEABORTINCOMPLETEMULTIPARTUPLOAD']._serialized_start=1086
  _globals['_LIFECYCLEABORTINCOMPLETEMULTIPARTUPLOAD']._serialized_end=1158
# @@protoc_insertion_point(module_scope)
