"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import nebius.common.v1.metadata_pb2
import nebius.iam.v1.access_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AuthPublicKey(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METADATA_FIELD_NUMBER: builtins.int
    SPEC_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    @property
    def metadata(self) -> nebius.common.v1.metadata_pb2.ResourceMetadata: ...
    @property
    def spec(self) -> global___AuthPublicKeySpec: ...
    @property
    def status(self) -> global___AuthPublicKeyStatus: ...
    def __init__(
        self,
        *,
        metadata: nebius.common.v1.metadata_pb2.ResourceMetadata | None = ...,
        spec: global___AuthPublicKeySpec | None = ...,
        status: global___AuthPublicKeyStatus | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["metadata", b"metadata", "spec", b"spec", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["metadata", b"metadata", "spec", b"spec", "status", b"status"]) -> None: ...

global___AuthPublicKey = AuthPublicKey

@typing.final
class AuthPublicKeySpec(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_FIELD_NUMBER: builtins.int
    EXPIRES_AT_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    description: builtins.str
    data: builtins.str
    @property
    def account(self) -> nebius.iam.v1.access_pb2.Account: ...
    @property
    def expires_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        account: nebius.iam.v1.access_pb2.Account | None = ...,
        expires_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        description: builtins.str = ...,
        data: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["account", b"account", "expires_at", b"expires_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account", b"account", "data", b"data", "description", b"description", "expires_at", b"expires_at"]) -> None: ...

global___AuthPublicKeySpec = AuthPublicKeySpec

@typing.final
class AuthPublicKeyStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _State:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[AuthPublicKeyStatus._State.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        STATE_UNSPECIFIED: AuthPublicKeyStatus._State.ValueType  # 0
        ACTIVE: AuthPublicKeyStatus._State.ValueType  # 1
        INACTIVE: AuthPublicKeyStatus._State.ValueType  # 2
        EXPIRED: AuthPublicKeyStatus._State.ValueType  # 3
        DELETING: AuthPublicKeyStatus._State.ValueType  # 4
        DELETED: AuthPublicKeyStatus._State.ValueType  # 5

    class State(_State, metaclass=_StateEnumTypeWrapper): ...
    STATE_UNSPECIFIED: AuthPublicKeyStatus.State.ValueType  # 0
    ACTIVE: AuthPublicKeyStatus.State.ValueType  # 1
    INACTIVE: AuthPublicKeyStatus.State.ValueType  # 2
    EXPIRED: AuthPublicKeyStatus.State.ValueType  # 3
    DELETING: AuthPublicKeyStatus.State.ValueType  # 4
    DELETED: AuthPublicKeyStatus.State.ValueType  # 5

    STATE_FIELD_NUMBER: builtins.int
    FINGERPRINT_FIELD_NUMBER: builtins.int
    ALGORITHM_FIELD_NUMBER: builtins.int
    KEY_SIZE_FIELD_NUMBER: builtins.int
    state: global___AuthPublicKeyStatus.State.ValueType
    fingerprint: builtins.str
    algorithm: builtins.str
    key_size: builtins.int
    def __init__(
        self,
        *,
        state: global___AuthPublicKeyStatus.State.ValueType = ...,
        fingerprint: builtins.str = ...,
        algorithm: builtins.str = ...,
        key_size: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["algorithm", b"algorithm", "fingerprint", b"fingerprint", "key_size", b"key_size", "state", b"state"]) -> None: ...

global___AuthPublicKeyStatus = AuthPublicKeyStatus
