"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import nebius.common.v1.metadata_pb2
import nebius.iam.v1.state_pb2
import nebius.iam.v1.suspension_state_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Container(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METADATA_FIELD_NUMBER: builtins.int
    SPEC_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    @property
    def metadata(self) -> nebius.common.v1.metadata_pb2.ResourceMetadata: ...
    @property
    def spec(self) -> global___ContainerSpec: ...
    @property
    def status(self) -> global___ContainerStatus: ...
    def __init__(
        self,
        *,
        metadata: nebius.common.v1.metadata_pb2.ResourceMetadata | None = ...,
        spec: global___ContainerSpec | None = ...,
        status: global___ContainerStatus | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["metadata", b"metadata", "spec", b"spec", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["metadata", b"metadata", "spec", b"spec", "status", b"status"]) -> None: ...

global___Container = Container

@typing.final
class ContainerSpec(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ContainerSpec = ContainerSpec

@typing.final
class ContainerStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUSPENSION_STATE_FIELD_NUMBER: builtins.int
    CONTAINER_STATE_FIELD_NUMBER: builtins.int
    suspension_state: nebius.iam.v1.suspension_state_pb2.SuspensionState.ValueType
    container_state: nebius.iam.v1.state_pb2.State.ValueType
    def __init__(
        self,
        *,
        suspension_state: nebius.iam.v1.suspension_state_pb2.SuspensionState.ValueType = ...,
        container_state: nebius.iam.v1.state_pb2.State.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["container_state", b"container_state", "suspension_state", b"suspension_state"]) -> None: ...

global___ContainerStatus = ContainerStatus
