"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import nebius.common.v1.metadata_pb2
import nebius.common.v1.operation_pb2
import nebius.iam.v1.federation_pb2
import nebius.iam.v1.federation_service_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class FederationServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Create: grpc.UnaryUnaryMultiCallable[
        nebius.iam.v1.federation_service_pb2.CreateFederationRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

    Get: grpc.UnaryUnaryMultiCallable[
        nebius.iam.v1.federation_service_pb2.GetFederationRequest,
        nebius.iam.v1.federation_pb2.Federation,
    ]

    GetByName: grpc.UnaryUnaryMultiCallable[
        nebius.common.v1.metadata_pb2.GetByNameRequest,
        nebius.iam.v1.federation_pb2.Federation,
    ]

    List: grpc.UnaryUnaryMultiCallable[
        nebius.iam.v1.federation_service_pb2.ListFederationsRequest,
        nebius.iam.v1.federation_service_pb2.ListFederationsResponse,
    ]

    Update: grpc.UnaryUnaryMultiCallable[
        nebius.iam.v1.federation_service_pb2.UpdateFederationRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

    Delete: grpc.UnaryUnaryMultiCallable[
        nebius.iam.v1.federation_service_pb2.DeleteFederationRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

class FederationServiceAsyncStub:
    Create: grpc.aio.UnaryUnaryMultiCallable[
        nebius.iam.v1.federation_service_pb2.CreateFederationRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

    Get: grpc.aio.UnaryUnaryMultiCallable[
        nebius.iam.v1.federation_service_pb2.GetFederationRequest,
        nebius.iam.v1.federation_pb2.Federation,
    ]

    GetByName: grpc.aio.UnaryUnaryMultiCallable[
        nebius.common.v1.metadata_pb2.GetByNameRequest,
        nebius.iam.v1.federation_pb2.Federation,
    ]

    List: grpc.aio.UnaryUnaryMultiCallable[
        nebius.iam.v1.federation_service_pb2.ListFederationsRequest,
        nebius.iam.v1.federation_service_pb2.ListFederationsResponse,
    ]

    Update: grpc.aio.UnaryUnaryMultiCallable[
        nebius.iam.v1.federation_service_pb2.UpdateFederationRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

    Delete: grpc.aio.UnaryUnaryMultiCallable[
        nebius.iam.v1.federation_service_pb2.DeleteFederationRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

class FederationServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Create(
        self,
        request: nebius.iam.v1.federation_service_pb2.CreateFederationRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.common.v1.operation_pb2.Operation, collections.abc.Awaitable[nebius.common.v1.operation_pb2.Operation]]: ...

    @abc.abstractmethod
    def Get(
        self,
        request: nebius.iam.v1.federation_service_pb2.GetFederationRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.iam.v1.federation_pb2.Federation, collections.abc.Awaitable[nebius.iam.v1.federation_pb2.Federation]]: ...

    @abc.abstractmethod
    def GetByName(
        self,
        request: nebius.common.v1.metadata_pb2.GetByNameRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.iam.v1.federation_pb2.Federation, collections.abc.Awaitable[nebius.iam.v1.federation_pb2.Federation]]: ...

    @abc.abstractmethod
    def List(
        self,
        request: nebius.iam.v1.federation_service_pb2.ListFederationsRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.iam.v1.federation_service_pb2.ListFederationsResponse, collections.abc.Awaitable[nebius.iam.v1.federation_service_pb2.ListFederationsResponse]]: ...

    @abc.abstractmethod
    def Update(
        self,
        request: nebius.iam.v1.federation_service_pb2.UpdateFederationRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.common.v1.operation_pb2.Operation, collections.abc.Awaitable[nebius.common.v1.operation_pb2.Operation]]: ...

    @abc.abstractmethod
    def Delete(
        self,
        request: nebius.iam.v1.federation_service_pb2.DeleteFederationRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.common.v1.operation_pb2.Operation, collections.abc.Awaitable[nebius.common.v1.operation_pb2.Operation]]: ...

def add_FederationServiceServicer_to_server(servicer: FederationServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
