# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nebius/iam/v1/federation_certificate_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nebius import annotations_pb2 as nebius_dot_annotations__pb2
from nebius.common.v1 import metadata_pb2 as nebius_dot_common_dot_v1_dot_metadata__pb2
from nebius.common.v1 import operation_pb2 as nebius_dot_common_dot_v1_dot_operation__pb2
from nebius.iam.v1 import federation_certificate_pb2 as nebius_dot_iam_dot_v1_dot_federation__certificate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2nebius/iam/v1/federation_certificate_service.proto\x12\rnebius.iam.v1\x1a\x18nebius/annotations.proto\x1a\x1fnebius/common/v1/metadata.proto\x1a nebius/common/v1/operation.proto\x1a*nebius/iam/v1/federation_certificate.proto\"\x92\x01\n\"CreateFederationCertificateRequest\x12\x34\n\x08metadata\x18\x01 \x01(\x0b\x32\".nebius.common.v1.ResourceMetadata\x12\x36\n\x04spec\x18\x02 \x01(\x0b\x32(.nebius.iam.v1.FederationCertificateSpec\"-\n\x1fGetFederationCertificateRequest\x12\n\n\x02id\x18\x01 \x01(\t\"l\n,ListFederationCertificateByFederationRequest\x12\x15\n\rfederation_id\x18\x01 \x01(\t\x12\x11\n\tpage_size\x18\x02 \x01(\x03\x12\x12\n\npage_token\x18\x03 \x01(\t\"\x92\x01\n\"UpdateFederationCertificateRequest\x12\x34\n\x08metadata\x18\x01 \x01(\x0b\x32\".nebius.common.v1.ResourceMetadata\x12\x36\n\x04spec\x18\x02 \x01(\x0b\x32(.nebius.iam.v1.FederationCertificateSpec\"0\n\"DeleteFederationCertificateRequest\x12\n\n\x02id\x18\x01 \x01(\t\"q\n!ListFederationCertificateResponse\x12\x33\n\x05items\x18\x01 \x03(\x0b\x32$.nebius.iam.v1.FederationCertificate\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t2\x99\x04\n\x1c\x46\x65\x64\x65rationCertificateService\x12X\n\x06\x43reate\x12\x31.nebius.iam.v1.CreateFederationCertificateRequest\x1a\x1b.nebius.common.v1.Operation\x12[\n\x03Get\x12..nebius.iam.v1.GetFederationCertificateRequest\x1a$.nebius.iam.v1.FederationCertificate\x12\x81\x01\n\x10ListByFederation\x12;.nebius.iam.v1.ListFederationCertificateByFederationRequest\x1a\x30.nebius.iam.v1.ListFederationCertificateResponse\x12X\n\x06Update\x12\x31.nebius.iam.v1.UpdateFederationCertificateRequest\x1a\x1b.nebius.common.v1.Operation\x12X\n\x06\x44\x65lete\x12\x31.nebius.iam.v1.DeleteFederationCertificateRequest\x1a\x1b.nebius.common.v1.Operation\x1a\n\xbaJ\x07\x63pl.iamBh\n\x14\x61i.nebius.pub.iam.v1B!FederationCertificateServiceProtoP\x01Z+github.com/nebius/gosdk/proto/nebius/iam/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nebius.iam.v1.federation_certificate_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024ai.nebius.pub.iam.v1B!FederationCertificateServiceProtoP\001Z+github.com/nebius/gosdk/proto/nebius/iam/v1'
  _FEDERATIONCERTIFICATESERVICE._options = None
  _FEDERATIONCERTIFICATESERVICE._serialized_options = b'\272J\007cpl.iam'
  _globals['_CREATEFEDERATIONCERTIFICATEREQUEST']._serialized_start=207
  _globals['_CREATEFEDERATIONCERTIFICATEREQUEST']._serialized_end=353
  _globals['_GETFEDERATIONCERTIFICATEREQUEST']._serialized_start=355
  _globals['_GETFEDERATIONCERTIFICATEREQUEST']._serialized_end=400
  _globals['_LISTFEDERATIONCERTIFICATEBYFEDERATIONREQUEST']._serialized_start=402
  _globals['_LISTFEDERATIONCERTIFICATEBYFEDERATIONREQUEST']._serialized_end=510
  _globals['_UPDATEFEDERATIONCERTIFICATEREQUEST']._serialized_start=513
  _globals['_UPDATEFEDERATIONCERTIFICATEREQUEST']._serialized_end=659
  _globals['_DELETEFEDERATIONCERTIFICATEREQUEST']._serialized_start=661
  _globals['_DELETEFEDERATIONCERTIFICATEREQUEST']._serialized_end=709
  _globals['_LISTFEDERATIONCERTIFICATERESPONSE']._serialized_start=711
  _globals['_LISTFEDERATIONCERTIFICATERESPONSE']._serialized_end=824
  _globals['_FEDERATIONCERTIFICATESERVICE']._serialized_start=827
  _globals['_FEDERATIONCERTIFICATESERVICE']._serialized_end=1364
# @@protoc_insertion_point(module_scope)
