# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nebius/iam/v1/group_membership.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from nebius.common.v1 import metadata_pb2 as nebius_dot_common_dot_v1_dot_metadata__pb2
from nebius import annotations_pb2 as nebius_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$nebius/iam/v1/group_membership.proto\x12\rnebius.iam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1b\x62uf/validate/validate.proto\x1a\x1fnebius/common/v1/metadata.proto\x1a\x18nebius/annotations.proto\"\x80\x02\n\x0fGroupMembership\x12<\n\x08metadata\x18\x01 \x01(\x0b\x32\".nebius.common.v1.ResourceMetadataB\x06\xbaH\x03\xc8\x01\x01\x12\x38\n\x04spec\x18\x02 \x01(\x0b\x32\".nebius.iam.v1.GroupMembershipSpecB\x06\xbaH\x03\xc8\x01\x01\x12:\n\x06status\x18\x03 \x01(\x0b\x32$.nebius.iam.v1.GroupMembershipStatusB\x04\xbaJ\x01\x05\x12\x33\n\trevoke_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x04\xbaJ\x01\x05:\x04\xbaJ\x01\x02\".\n\x13GroupMembershipSpec\x12\x17\n\tmember_id\x18\x01 \x01(\tB\x04\xbaJ\x01\x02\"\x17\n\x15GroupMembershipStatusB[\n\x14\x61i.nebius.pub.iam.v1B\x14GroupMembershipProtoP\x01Z+github.com/nebius/gosdk/proto/nebius/iam/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nebius.iam.v1.group_membership_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024ai.nebius.pub.iam.v1B\024GroupMembershipProtoP\001Z+github.com/nebius/gosdk/proto/nebius/iam/v1'
  _GROUPMEMBERSHIP.fields_by_name['metadata']._options = None
  _GROUPMEMBERSHIP.fields_by_name['metadata']._serialized_options = b'\272H\003\310\001\001'
  _GROUPMEMBERSHIP.fields_by_name['spec']._options = None
  _GROUPMEMBERSHIP.fields_by_name['spec']._serialized_options = b'\272H\003\310\001\001'
  _GROUPMEMBERSHIP.fields_by_name['status']._options = None
  _GROUPMEMBERSHIP.fields_by_name['status']._serialized_options = b'\272J\001\005'
  _GROUPMEMBERSHIP.fields_by_name['revoke_at']._options = None
  _GROUPMEMBERSHIP.fields_by_name['revoke_at']._serialized_options = b'\272J\001\005'
  _GROUPMEMBERSHIP._options = None
  _GROUPMEMBERSHIP._serialized_options = b'\272J\001\002'
  _GROUPMEMBERSHIPSPEC.fields_by_name['member_id']._options = None
  _GROUPMEMBERSHIPSPEC.fields_by_name['member_id']._serialized_options = b'\272J\001\002'
  _globals['_GROUPMEMBERSHIP']._serialized_start=177
  _globals['_GROUPMEMBERSHIP']._serialized_end=433
  _globals['_GROUPMEMBERSHIPSPEC']._serialized_start=435
  _globals['_GROUPMEMBERSHIPSPEC']._serialized_end=481
  _globals['_GROUPMEMBERSHIPSTATUS']._serialized_start=483
  _globals['_GROUPMEMBERSHIPSTATUS']._serialized_end=506
# @@protoc_insertion_point(module_scope)
