"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import nebius.common.v1.metadata_pb2
import nebius.iam.v1.group_membership_pb2
import nebius.iam.v1.group_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CreateGroupMembershipRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METADATA_FIELD_NUMBER: builtins.int
    SPEC_FIELD_NUMBER: builtins.int
    REVOKE_AFTER_HOURS_FIELD_NUMBER: builtins.int
    revoke_after_hours: builtins.int
    @property
    def metadata(self) -> nebius.common.v1.metadata_pb2.ResourceMetadata: ...
    @property
    def spec(self) -> nebius.iam.v1.group_membership_pb2.GroupMembershipSpec: ...
    def __init__(
        self,
        *,
        metadata: nebius.common.v1.metadata_pb2.ResourceMetadata | None = ...,
        spec: nebius.iam.v1.group_membership_pb2.GroupMembershipSpec | None = ...,
        revoke_after_hours: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["metadata", b"metadata", "spec", b"spec"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["metadata", b"metadata", "revoke_after_hours", b"revoke_after_hours", "spec", b"spec"]) -> None: ...

global___CreateGroupMembershipRequest = CreateGroupMembershipRequest

@typing.final
class DeleteGroupMembershipRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___DeleteGroupMembershipRequest = DeleteGroupMembershipRequest

@typing.final
class GetGroupMembershipRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___GetGroupMembershipRequest = GetGroupMembershipRequest

@typing.final
class ListGroupMembershipsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_ID_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    parent_id: builtins.str
    page_size: builtins.int
    """Default value: 10"""
    page_token: builtins.str
    filter: builtins.str
    def __init__(
        self,
        *,
        parent_id: builtins.str = ...,
        page_size: builtins.int | None = ...,
        page_token: builtins.str = ...,
        filter: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_page_size", b"_page_size", "page_size", b"page_size"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_page_size", b"_page_size", "filter", b"filter", "page_size", b"page_size", "page_token", b"page_token", "parent_id", b"parent_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_page_size", b"_page_size"]) -> typing.Literal["page_size"] | None: ...

global___ListGroupMembershipsRequest = ListGroupMembershipsRequest

@typing.final
class ListMemberOfRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBJECT_ID_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    subject_id: builtins.str
    """Requested subject id. Can be tenant user account id or service account id."""
    page_size: builtins.int
    """Default value: 10"""
    page_token: builtins.str
    filter: builtins.str
    def __init__(
        self,
        *,
        subject_id: builtins.str = ...,
        page_size: builtins.int | None = ...,
        page_token: builtins.str = ...,
        filter: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_page_size", b"_page_size", "page_size", b"page_size"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_page_size", b"_page_size", "filter", b"filter", "page_size", b"page_size", "page_token", b"page_token", "subject_id", b"subject_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_page_size", b"_page_size"]) -> typing.Literal["page_size"] | None: ...

global___ListMemberOfRequest = ListMemberOfRequest

@typing.final
class ListGroupMembershipsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MEMBERSHIPS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    @property
    def memberships(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[nebius.iam.v1.group_membership_pb2.GroupMembership]:
        """Members of the group. Can be tenant user account ids or service account ids."""

    def __init__(
        self,
        *,
        memberships: collections.abc.Iterable[nebius.iam.v1.group_membership_pb2.GroupMembership] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["memberships", b"memberships", "next_page_token", b"next_page_token"]) -> None: ...

global___ListGroupMembershipsResponse = ListGroupMembershipsResponse

@typing.final
class ListMemberOfResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ITEMS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    @property
    def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[nebius.iam.v1.group_pb2.Group]:
        """Groups that requested entity is a member of"""

    def __init__(
        self,
        *,
        items: collections.abc.Iterable[nebius.iam.v1.group_pb2.Group] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["items", b"items", "next_page_token", b"next_page_token"]) -> None: ...

global___ListMemberOfResponse = ListMemberOfResponse
