"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.timestamp_pb2
import nebius.common.v1.metadata_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GroupMembership(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METADATA_FIELD_NUMBER: builtins.int
    SPEC_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REVOKE_AT_FIELD_NUMBER: builtins.int
    @property
    def metadata(self) -> nebius.common.v1.metadata_pb2.ResourceMetadata: ...
    @property
    def spec(self) -> global___GroupMembershipSpec: ...
    @property
    def status(self) -> global___GroupMembershipStatus:
        """Dummy field for compliance with terraform resource generator."""

    @property
    def revoke_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        metadata: nebius.common.v1.metadata_pb2.ResourceMetadata | None = ...,
        spec: global___GroupMembershipSpec | None = ...,
        status: global___GroupMembershipStatus | None = ...,
        revoke_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["metadata", b"metadata", "revoke_at", b"revoke_at", "spec", b"spec", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["metadata", b"metadata", "revoke_at", b"revoke_at", "spec", b"spec", "status", b"status"]) -> None: ...

global___GroupMembership = GroupMembership

@typing.final
class GroupMembershipSpec(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MEMBER_ID_FIELD_NUMBER: builtins.int
    member_id: builtins.str
    """Member of the group. Can be tenant user account id or service account id."""
    def __init__(
        self,
        *,
        member_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["member_id", b"member_id"]) -> None: ...

global___GroupMembershipSpec = GroupMembershipSpec

@typing.final
class GroupMembershipStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GroupMembershipStatus = GroupMembershipStatus
