"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import nebius.iam.v1.group_pb2
import nebius.iam.v1.group_service_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class GroupServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Get: grpc.UnaryUnaryMultiCallable[
        nebius.iam.v1.group_service_pb2.GetGroupRequest,
        nebius.iam.v1.group_pb2.Group,
    ]

    GetByName: grpc.UnaryUnaryMultiCallable[
        nebius.iam.v1.group_service_pb2.GetGroupByNameRequest,
        nebius.iam.v1.group_pb2.Group,
    ]

    List: grpc.UnaryUnaryMultiCallable[
        nebius.iam.v1.group_service_pb2.ListGroupsRequest,
        nebius.iam.v1.group_service_pb2.ListGroupsResponse,
    ]

class GroupServiceAsyncStub:
    Get: grpc.aio.UnaryUnaryMultiCallable[
        nebius.iam.v1.group_service_pb2.GetGroupRequest,
        nebius.iam.v1.group_pb2.Group,
    ]

    GetByName: grpc.aio.UnaryUnaryMultiCallable[
        nebius.iam.v1.group_service_pb2.GetGroupByNameRequest,
        nebius.iam.v1.group_pb2.Group,
    ]

    List: grpc.aio.UnaryUnaryMultiCallable[
        nebius.iam.v1.group_service_pb2.ListGroupsRequest,
        nebius.iam.v1.group_service_pb2.ListGroupsResponse,
    ]

class GroupServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Get(
        self,
        request: nebius.iam.v1.group_service_pb2.GetGroupRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.iam.v1.group_pb2.Group, collections.abc.Awaitable[nebius.iam.v1.group_pb2.Group]]: ...

    @abc.abstractmethod
    def GetByName(
        self,
        request: nebius.iam.v1.group_service_pb2.GetGroupByNameRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.iam.v1.group_pb2.Group, collections.abc.Awaitable[nebius.iam.v1.group_pb2.Group]]: ...

    @abc.abstractmethod
    def List(
        self,
        request: nebius.iam.v1.group_service_pb2.ListGroupsRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.iam.v1.group_service_pb2.ListGroupsResponse, collections.abc.Awaitable[nebius.iam.v1.group_service_pb2.ListGroupsResponse]]: ...

def add_GroupServiceServicer_to_server(servicer: GroupServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
