"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import nebius.iam.v1.token_service_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class IdentityServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    ExchangeToken: grpc.UnaryUnaryMultiCallable[
        nebius.iam.v1.token_service_pb2.ExchangeTokenRequest,
        nebius.iam.v1.token_service_pb2.CreateTokenResponse,
    ]

class IdentityServiceAsyncStub:
    ExchangeToken: grpc.aio.UnaryUnaryMultiCallable[
        nebius.iam.v1.token_service_pb2.ExchangeTokenRequest,
        nebius.iam.v1.token_service_pb2.CreateTokenResponse,
    ]

class IdentityServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def ExchangeToken(
        self,
        request: nebius.iam.v1.token_service_pb2.ExchangeTokenRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.iam.v1.token_service_pb2.CreateTokenResponse, collections.abc.Awaitable[nebius.iam.v1.token_service_pb2.CreateTokenResponse]]: ...

def add_IdentityServiceServicer_to_server(servicer: IdentityServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
