"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import nebius.common.v1.operation_pb2
import nebius.iam.v1.service_account_pb2
import nebius.iam.v1.service_account_service_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class ServiceAccountServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Create: grpc.UnaryUnaryMultiCallable[
        nebius.iam.v1.service_account_service_pb2.CreateServiceAccountRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

    Get: grpc.UnaryUnaryMultiCallable[
        nebius.iam.v1.service_account_service_pb2.GetServiceAccountRequest,
        nebius.iam.v1.service_account_pb2.ServiceAccount,
    ]

    GetByName: grpc.UnaryUnaryMultiCallable[
        nebius.iam.v1.service_account_service_pb2.GetServiceAccountByNameRequest,
        nebius.iam.v1.service_account_pb2.ServiceAccount,
    ]

    List: grpc.UnaryUnaryMultiCallable[
        nebius.iam.v1.service_account_service_pb2.ListServiceAccountRequest,
        nebius.iam.v1.service_account_service_pb2.ListServiceAccountResponse,
    ]

    Update: grpc.UnaryUnaryMultiCallable[
        nebius.iam.v1.service_account_service_pb2.UpdateServiceAccountRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

    Delete: grpc.UnaryUnaryMultiCallable[
        nebius.iam.v1.service_account_service_pb2.DeleteServiceAccountRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

class ServiceAccountServiceAsyncStub:
    Create: grpc.aio.UnaryUnaryMultiCallable[
        nebius.iam.v1.service_account_service_pb2.CreateServiceAccountRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

    Get: grpc.aio.UnaryUnaryMultiCallable[
        nebius.iam.v1.service_account_service_pb2.GetServiceAccountRequest,
        nebius.iam.v1.service_account_pb2.ServiceAccount,
    ]

    GetByName: grpc.aio.UnaryUnaryMultiCallable[
        nebius.iam.v1.service_account_service_pb2.GetServiceAccountByNameRequest,
        nebius.iam.v1.service_account_pb2.ServiceAccount,
    ]

    List: grpc.aio.UnaryUnaryMultiCallable[
        nebius.iam.v1.service_account_service_pb2.ListServiceAccountRequest,
        nebius.iam.v1.service_account_service_pb2.ListServiceAccountResponse,
    ]

    Update: grpc.aio.UnaryUnaryMultiCallable[
        nebius.iam.v1.service_account_service_pb2.UpdateServiceAccountRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

    Delete: grpc.aio.UnaryUnaryMultiCallable[
        nebius.iam.v1.service_account_service_pb2.DeleteServiceAccountRequest,
        nebius.common.v1.operation_pb2.Operation,
    ]

class ServiceAccountServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Create(
        self,
        request: nebius.iam.v1.service_account_service_pb2.CreateServiceAccountRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.common.v1.operation_pb2.Operation, collections.abc.Awaitable[nebius.common.v1.operation_pb2.Operation]]: ...

    @abc.abstractmethod
    def Get(
        self,
        request: nebius.iam.v1.service_account_service_pb2.GetServiceAccountRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.iam.v1.service_account_pb2.ServiceAccount, collections.abc.Awaitable[nebius.iam.v1.service_account_pb2.ServiceAccount]]: ...

    @abc.abstractmethod
    def GetByName(
        self,
        request: nebius.iam.v1.service_account_service_pb2.GetServiceAccountByNameRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.iam.v1.service_account_pb2.ServiceAccount, collections.abc.Awaitable[nebius.iam.v1.service_account_pb2.ServiceAccount]]: ...

    @abc.abstractmethod
    def List(
        self,
        request: nebius.iam.v1.service_account_service_pb2.ListServiceAccountRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.iam.v1.service_account_service_pb2.ListServiceAccountResponse, collections.abc.Awaitable[nebius.iam.v1.service_account_service_pb2.ListServiceAccountResponse]]: ...

    @abc.abstractmethod
    def Update(
        self,
        request: nebius.iam.v1.service_account_service_pb2.UpdateServiceAccountRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.common.v1.operation_pb2.Operation, collections.abc.Awaitable[nebius.common.v1.operation_pb2.Operation]]: ...

    @abc.abstractmethod
    def Delete(
        self,
        request: nebius.iam.v1.service_account_service_pb2.DeleteServiceAccountRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.common.v1.operation_pb2.Operation, collections.abc.Awaitable[nebius.common.v1.operation_pb2.Operation]]: ...

def add_ServiceAccountServiceServicer_to_server(servicer: ServiceAccountServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
