"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import nebius.iam.v1.session_management_service_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class SessionManagementServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Revoke: grpc.UnaryUnaryMultiCallable[
        nebius.iam.v1.session_management_service_pb2.RevokeSessionRequest,
        nebius.iam.v1.session_management_service_pb2.RevokeSessionResponse,
    ]

class SessionManagementServiceAsyncStub:
    Revoke: grpc.aio.UnaryUnaryMultiCallable[
        nebius.iam.v1.session_management_service_pb2.RevokeSessionRequest,
        nebius.iam.v1.session_management_service_pb2.RevokeSessionResponse,
    ]

class SessionManagementServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Revoke(
        self,
        request: nebius.iam.v1.session_management_service_pb2.RevokeSessionRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.iam.v1.session_management_service_pb2.RevokeSessionResponse, collections.abc.Awaitable[nebius.iam.v1.session_management_service_pb2.RevokeSessionResponse]]: ...

def add_SessionManagementServiceServicer_to_server(servicer: SessionManagementServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
