"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class RevokeSessionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVICE_ACCOUNT_ID_FIELD_NUMBER: builtins.int
    ALL_MY_ACTIVE_FIELD_NUMBER: builtins.int
    TENANT_USER_ACCOUNT_ID_FIELD_NUMBER: builtins.int
    service_account_id: builtins.str
    """revoke all for specific service account - to revoke logout from all sessions for user"""
    all_my_active: builtins.bool
    """revoke all active session of current user"""
    tenant_user_account_id: builtins.str
    """revoke all for specific tenant user - to revoke logout from all sessions for user"""
    def __init__(
        self,
        *,
        service_account_id: builtins.str = ...,
        all_my_active: builtins.bool = ...,
        tenant_user_account_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["all_my_active", b"all_my_active", "revoke", b"revoke", "service_account_id", b"service_account_id", "tenant_user_account_id", b"tenant_user_account_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["all_my_active", b"all_my_active", "revoke", b"revoke", "service_account_id", b"service_account_id", "tenant_user_account_id", b"tenant_user_account_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["revoke", b"revoke"]) -> typing.Literal["service_account_id", "all_my_active", "tenant_user_account_id"] | None: ...

global___RevokeSessionRequest = RevokeSessionRequest

@typing.final
class RevokeSessionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RevokeSessionResponse = RevokeSessionResponse
