"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _State:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_State.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    STATE_UNSPECIFIED: _State.ValueType  # 0
    ACTIVE: _State.ValueType  # 1
    SCHEDULING_FOR_DELETION: _State.ValueType  # 2
    SCHEDULED_FOR_DELETION: _State.ValueType  # 3
    SCHEDULING_FOR_DELETION_BY_PARENT: _State.ValueType  # 4
    SCHEDULED_FOR_DELETION_BY_PARENT: _State.ValueType  # 5
    UNDELETING: _State.ValueType  # 6
    PURGING: _State.ValueType  # 7
    PURGED: _State.ValueType  # 8
    CREATING: _State.ValueType  # 1001
    """DRAFT = 1000;"""

class State(_State, metaclass=_StateEnumTypeWrapper): ...

STATE_UNSPECIFIED: State.ValueType  # 0
ACTIVE: State.ValueType  # 1
SCHEDULING_FOR_DELETION: State.ValueType  # 2
SCHEDULED_FOR_DELETION: State.ValueType  # 3
SCHEDULING_FOR_DELETION_BY_PARENT: State.ValueType  # 4
SCHEDULED_FOR_DELETION_BY_PARENT: State.ValueType  # 5
UNDELETING: State.ValueType  # 6
PURGING: State.ValueType  # 7
PURGED: State.ValueType  # 8
CREATING: State.ValueType  # 1001
"""DRAFT = 1000;"""
global___State = State
