"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _SuspensionState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SuspensionStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SuspensionState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SUSPENSION_STATE_UNSPECIFIED: _SuspensionState.ValueType  # 0
    NONE: _SuspensionState.ValueType  # 1
    SUSPENDING: _SuspensionState.ValueType  # 2
    SUSPENDED: _SuspensionState.ValueType  # 3
    RESUMING: _SuspensionState.ValueType  # 4

class SuspensionState(_SuspensionState, metaclass=_SuspensionStateEnumTypeWrapper): ...

SUSPENSION_STATE_UNSPECIFIED: SuspensionState.ValueType  # 0
NONE: SuspensionState.ValueType  # 1
SUSPENDING: SuspensionState.ValueType  # 2
SUSPENDED: SuspensionState.ValueType  # 3
RESUMING: SuspensionState.ValueType  # 4
global___SuspensionState = SuspensionState
