"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import nebius.iam.v1.tenant_user_account_pb2
import nebius.iam.v1.tenant_user_account_with_attributes_service_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class TenantUserAccountWithAttributesServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Get: grpc.UnaryUnaryMultiCallable[
        nebius.iam.v1.tenant_user_account_with_attributes_service_pb2.GetTenantUserAccountWithAttributesRequest,
        nebius.iam.v1.tenant_user_account_pb2.TenantUserAccountWithAttributes,
    ]

    List: grpc.UnaryUnaryMultiCallable[
        nebius.iam.v1.tenant_user_account_with_attributes_service_pb2.ListTenantUserAccountsWithAttributesRequest,
        nebius.iam.v1.tenant_user_account_with_attributes_service_pb2.ListTenantUserAccountsWithAttributesResponse,
    ]

class TenantUserAccountWithAttributesServiceAsyncStub:
    Get: grpc.aio.UnaryUnaryMultiCallable[
        nebius.iam.v1.tenant_user_account_with_attributes_service_pb2.GetTenantUserAccountWithAttributesRequest,
        nebius.iam.v1.tenant_user_account_pb2.TenantUserAccountWithAttributes,
    ]

    List: grpc.aio.UnaryUnaryMultiCallable[
        nebius.iam.v1.tenant_user_account_with_attributes_service_pb2.ListTenantUserAccountsWithAttributesRequest,
        nebius.iam.v1.tenant_user_account_with_attributes_service_pb2.ListTenantUserAccountsWithAttributesResponse,
    ]

class TenantUserAccountWithAttributesServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Get(
        self,
        request: nebius.iam.v1.tenant_user_account_with_attributes_service_pb2.GetTenantUserAccountWithAttributesRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.iam.v1.tenant_user_account_pb2.TenantUserAccountWithAttributes, collections.abc.Awaitable[nebius.iam.v1.tenant_user_account_pb2.TenantUserAccountWithAttributes]]: ...

    @abc.abstractmethod
    def List(
        self,
        request: nebius.iam.v1.tenant_user_account_with_attributes_service_pb2.ListTenantUserAccountsWithAttributesRequest,
        context: _ServicerContext,
    ) -> typing.Union[nebius.iam.v1.tenant_user_account_with_attributes_service_pb2.ListTenantUserAccountsWithAttributesResponse, collections.abc.Awaitable[nebius.iam.v1.tenant_user_account_with_attributes_service_pb2.ListTenantUserAccountsWithAttributesResponse]]: ...

def add_TenantUserAccountWithAttributesServiceServicer_to_server(servicer: TenantUserAccountWithAttributesServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
